version: '3'

services:
  database:
    image: 'mongo'
    container_name: mongo
    restart: always
    env_file:
      - ./database/db_credentials.env
    volumes:
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./database/mongo-volume:/data/db
    ports:
      - '27017:27017'

  rabbitmq:
    image: "rabbitmq:3-management"
    hostname: "rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret_cookie"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq"
    volumes:
      - "./event-queue/enabled_plugins:/etc/rabbitmq/enabled_plugins"

  node:
    build: .
    command: 'npm run dev'
    ports:
    - '8500:8500'
    links:
      - database
      - rabbitmq
    depends_on:
      - database
      - rabbitmq