version: '3'

services:
  database:
    image: 'mongo'
    container_name: mongo1
    restart: always
    env_file:
      - ./database/db_credentials.env
    volumes:
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./database/mongo-volume:/data/db
    ports:
      - '27017:27017'

  node:
    image: 'node:12'
    user: 'node'
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./api/code:/home/node/app
    ports:
      - '8500:8500'
    command: 'npm run dev'
    links:
      - database
    depends_on:
      - database