---
version: '3.8'
services:
 app:
  build: .
  image: mon-mongo
  ports:
   - "27017:27017"
  
 mongo:
  image: "mongo"
  restart: always
  environment:
   MONGO_INITDB_ROOT_USERNAME: root
   MONGO_INITDB_ROOT_PASSWORD: root
   MONGO_INITDB_ROOT_DATABASE: dbmongo
  volumes:
   - ./data:/datab/db
