version: '3'

services:
  node:
    image: esgimicroci/al2-events
    container_name: al2-events
    ports:
    - '8500:8500'
    links:
      - database
      - rabbitmq
    depends_on:
      - database
      - rabbitmq
    restart: always